site_name: HD Admin

nav:
    - Home: index.md
    - About: about.md

theme:
  name: material
  favicon: "img/LogoWhite64.png"
  logo: "img/LogoWhite64.png"
  palette:
    primary: black
    accent: black
  highlightjs: true
  hljs_languages:
    - lua