site_name: HD Admin
site_url: https://hd.community/software
repo_url: https://github.com/1ForeverHD/HDAdmin
repo_name: HDAdmin

nav:
    - Home: index.md
    - Setup:
        - Download: about.md
        - Config:
            - Ranks: about.md
            - Settings: about.md
        - Extensions: about.md
    - Framework:
        - Execution: about.md
        - Services & Controllers: about.md
        - Modules: about.md
    - Module Docs:
        - Core:
            - Client:
                - Modules:
                    Test: index.md
            - Server:
                - Modules:
                    Test: index.md
            - Shared:
                - Modules:
                    Test: index.md
        - Projects:
            - DataStore+:
                About: module_docs\projects\datastoreplus\about.md
                UserService: module_docs\projects\datastoreplus\userservice.md
                User: module_docs\projects\datastoreplus\user.md
            - Table+:
                About: module_docs\projects\tableplus\about.md
                Table: module_docs\projects\tableplus\table.md
            - Topbar+:
                About: module_docs\projects\topbarplus\about.md
                IconController: module_docs\projects\topbarplus\iconcontroller.md
                Icon: module_docs\projects\topbarplus\icon.md
            - Zone+:
                About: module_docs\projects\zoneplus\about.md
                ZoneService: module_docs\projects\zoneplus\zoneservice.md
                Zone: module_docs\projects\zoneplus\zone.md

theme:
  name: material
  favicon: "img/LogoWhite64.png"
  logo: "img/LogoWhite64.png"
  palette:
    primary: black
    accent: black
  highlightjs: true
  hljs_languages:
    - lua