name: PublishToRoblox

on:
  push:
    branches: #  Act on master branch commit
    - master

jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: rojo-rbx/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Deploy
      run: |
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 4664437268 Projects/Zone+
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 4926442976 Utility/DirectoryService
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 5086306120 Utility/Maid
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 5091723186 Utility/Promise
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 4893141590 Utility/Signal
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }} # d
