name: PublishToRoblox

on:
  push:
    branches: #  Act on master branch commit
    - master

jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: rojo-rbx/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Deploy
      run: |
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 4664437268 Projects/Zone+
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 4874365424 Projects/Topbar+
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 4734187373 Projects/Table+
        rojo upload --cookie "$ROBLOSECURITY" --asset_id 4643209210 Projects/DataStore+
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
