site_name: HD Admin
site_url: https://hd.community/software
repo_url: https://github.com/1ForeverHD/HDAdmin
repo_name: HDAdmin
edit_uri: edit/master/mkdocs/docs/

nav:
    - Home: index.md
    - Setup:
        - Download: about.md
        - Config:
            - Ranks: about.md
            - Settings: about.md
        - Extensions: about.md
    - Framework:
        - Execution: about.md
        - Services & Controllers: about.md
        - Modules: about.md
    - Module Docs:
        - Core:
            - Client:
                - Modules:
                    Test: index.md
            - Server:
                - Modules:
                    Test: index.md
            - Shared:
                - Modules:
                    Test: index.md
        - Projects:
            - DataStore+:
                About: projects\datastoreplus\about.md
                UserService: projects\datastoreplus\userservice.md
                User: projects\datastoreplus\user.md
                State: projects\datastoreplus\state.md
            - Topbar+:
                About: projects\topbarplus\about.md
                IconController: projects\topbarplus\iconcontroller.md
                Icon: projects\topbarplus\icon.md
                Dropdown: projects\topbarplus\dropdown.md
            - Zone+:
                About: projects\zoneplus\about.md
                ZoneService: projects\zoneplus\zoneservice.md
                Zone: projects\zoneplus\zone.md

theme:
  name: material
  favicon: "img/LogoWhite64.png"
  logo: "img/LogoWhite64.png"
  palette:
    primary: black
    accent: grey
  highlightjs: true
  hljs_languages:
    - lua

extra_css:
  - stylesheets/tags.css
  - stylesheets/dark_theme.css
  - stylesheets/monokai.css

extra_javascript:
#  - javascripts/tags.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      baselevel: 2
  - codehilite:
      guess_lang: false
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_div_format